### ISSUE TITLE
Unable to reproduce the wall trap method

### ISSUE THREAD

**Issue by Reeenatu** [Supalosa/osrs-colosseum#7] opened 2024-03-27 18:27 UTC
https://streamable.com/oxj6wp As you can see on the video the melee should be trapped on that tile, for some reason im unable to reproduce this situation on the simulator.

**Comment by Supalosa** [comment] 2024-03-27 23:37
This is a duplicate of #5 and fixed in #6

**Comment by Supalosa** [comment] 2024-03-27 23:47
Actually I will also need to review the NPC pathing logic. Right now I don't allow diagonal movement across corners, which means he won't go into that gap. 

![image](https://github.com/Supalosa/osrs-colosseum/assets/1549353/ef0d75e1-478c-487b-bd18-ad3aa7c9dda3)

**Comment by Supalosa** [comment] 2024-03-28 00:09
Tested with Robo and it appears that only 1x1 mobs are restricted from cutting corners, adjusted accordingly and this now works on the dev branch https://deploy-preview-6--osrs-colosseum.netlify.app/

**Comment by Supalosa** [comment] 2024-03-28 05:30
It's merged now - let me know if you still see this issue

**Closed by Supalosa** 2024-03-28 05:30 UTC
